# Format: https://dart.dev/tools/pub/pubspec

name: pxl
version: 0.0.0
publish_to: none
environment:
  sdk: ^3.5.0

dependencies:
  lodim: any
  meta: ^1.15.0

dev_dependencies:
  checks: ^0.3.0
  oath: ^0.2.1
  test: ^1.25.8

dependency_overrides:
  lodim:
    git:
      url: https://github.com/matanlurey/lodim
      ref: 2145724012eca83036afbd154473fca6a3d53d8d
